extends "res://tests/chessis13_test.gd"

func matching_cache(ply: int) -> bool:
	if app.ui.live_details.is_empty(): return false
	return app.ui.live_details[1].pv == report.samples[ply].candidates[0].pv and app.ui.live_key == report.game.positions[ply].key()

func run(instance) -> void:
	app=instance
	output=ProjectSettings.globalize_path("res://../review/app/chessis16/ui")
	if "--chessis24-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis24/chessis16_test")
	if "--chessis23-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis23/chessis16_test")
	if "--chessis22-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis22/chessis16_test")
	if "--chessis21-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis21/chessis16_test")
	if "--chessis17-regression" in OS.get_cmdline_user_args(): output=ProjectSettings.globalize_path("res://../review/app/chessis17/selection-ui")
	if "--chessis18-regression" in OS.get_cmdline_user_args(): output=ProjectSettings.globalize_path("res://../review/app/chessis18/selection-ui")
	if "--chessis19-regression" in OS.get_cmdline_user_args(): output=ProjectSettings.globalize_path("res://../review/app/chessis19/selection-ui")
	if "--chessis20-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis20/chessis16_test")
	DirAccess.make_dir_recursive_absolute(output)
	app.records.root=output.path_join("records")
	app.ui.tutorial.progress_path=output.path_join("learning-test.json")
	app.get_tree().create_timer(160).timeout.connect(func(): app.get_tree().quit(2))
	app._start_match("local",1,2,"basic")
	app.ui.close()
	await play("9g9f")
	live=app.game
	saved_live=live.to_data().duplicate(true)
	report=app.ui.report
	practice=app.ui.practice
	app.preferences.studio.analysis_lines=1
	var source=app.Game.new()
	for value in ["7g7f","3c3d","8h2b+","3a2b","B*4e"]:
		check(source.play(app.Codec.parse_move(value,source.position)),"legal real-engine fixture " + value)
	source.metadata={"先手":"报告先手","后手":"报告后手"}
	report.start(source,true,{"deep_mode":"time","deep_time":0.3,"deep_lines":3})
	check(await until(func(): return not report.running,20),"actual engine completes report with three alternatives")
	check(report.error.is_empty() and report.samples.size()==6,"all fixture positions have engine evidence")
	var saved_report=report.game.to_data().duplicate(true)
	FileAccess.open(output.path_join("actual-report.json"),FileAccess.WRITE).store_string(JSON.stringify({"source":saved_report,"samples":report.samples,"rows":report.rows},"  "))
	for mode in ["dark","light"]:
		app.set_preference("color_mode",mode)
		for dimensions in [Vector2i(360,760),Vector2i(393,852),Vector2i(852,393),Vector2i(1100,800)]:
			await resize(dimensions)
			app.ui.show_report()
			app.ui.select_report_move(3)
			app.ui.page_scroll.ensure_control_visible(app.ui.report_selection)
			await settle()
			var card=app.ui.page.find_child("ReportMoveCard",true,false)
			check(card!=null and card.size.y>=82 and card.size.y<=170,"selected move remains a compact card")
			check(card.get_global_rect().end.x<=app.ui.page.get_global_rect().end.x,"selected card fits report width")
			check(card.find_child("ReportMoveTitle",true,false).get_line_count()==1,"move title remains single-line")
			check(card.find_child("DismissReportMove",true,false).get_theme_color("font_color").get_luminance()>0.8,"card close control remains legible on dark surface in either theme")
			check(card.find_child("ReportStateBefore",true,false).text==preload("res://scripts/shogi_report_move.gd").state_label(report.samples[2]),"before state comes from actual prior sample")
			check(card.find_child("ReportScoreAfter",true,false).text==preload("res://scripts/shogi_report_move.gd").score_label(report.samples[3]),"after score comes from actual selected sample")
			await capture("selected-"+mode+"-%dx%d" % [dimensions.x,dimensions.y])
	await resize(Vector2i(393,852))
	app.set_preference("color_mode","dark")
	app.ui.show_report()
	app.ui.select_report_move(3)
	await press("OpenReportMoveBoard")
	check(app.ui.page==null and app.review_game==report.game and app.replay_index==3,"card touch opens exact report position")
	check(await until(func(): return matching_cache(3)),"board candidate lines use selected position rather than previous ply")
	check(app.ui.pv_rows.size()==3,"deep report lines remain independent of one-line live preference")
	check(not app.ui.live_enabled and app.engine_context.is_empty(),"saved report display does not start competing live search")
	await capture("report-board-lines")
	await until(func(): return app.motion_progress>=1)
	app.ui.show_history(2)
	var motion_frames = []
	var motion_started = Time.get_ticks_msec()
	while Time.get_ticks_msec() - motion_started < 1500:
		await RenderingServer.frame_post_draw
		motion_frames.append({"ms": Time.get_ticks_msec() - motion_started, "progress": app.motion_progress})
		if app.motion_progress >= 1: break
	FileAccess.open(output.path_join("replay-motion.json"), FileAccess.WRITE).store_string(JSON.stringify(motion_frames, "  "))
	check(motion_frames.any(func(frame): return frame.progress > 0 and frame.progress < 1), "report replay renders intermediate piece positions")
	check(matching_cache(2),"candidate root follows animated history change")
	app.ui.show_history(1)
	app.ui.show_history(4)
	check(await until(func(): return app.replay_index==4 and app.motion_progress>=1),"rapid navigation finishes at most recent requested ply")
	check(matching_cache(4),"rapid history navigation never leaves stale candidate lines")
	await press("ReportMoveDetails")
	check(app.ui.page_name=="report-move" and app.ui.page.find_child("ReportMoveExplanation",true,false)!=null,"board details retains classification explanation")
	await capture("move-details")
	app.set_preference("color_mode","light")
	app.ui.show_report_move_details(4)
	await capture("move-details-light")
	app.set_preference("color_mode","dark")
	app.ui.show_report_move_details(4)
	await press("ReportCandidatePreview1")
	check(app.ui.pv_context.get("details",false) and app.review_game.initial_sfen==app.Codec.sfen(report.game.positions[3]),"detailed alternative preview begins before the selected move")
	await capture("detail-alternative")
	app.ui.stop_pv()
	await settle()
	check(app.ui.page_name=="report-move" and app.ui.report_selected_ply==4,"preview returns to selected move details")
	app.ui.back()
	check(app.ui.page==null and app.replay_index==4 and matching_cache(4),"details back returns to matching board snapshot")
	app.ui.change_lines(-1)
	check(app.ui.pv_rows.size()==2 and app.preferences.studio.analysis_lines==1,"snapshot line visibility does not rewrite live settings")
	app.ui.preview_pv(1)
	check(not app.ui.pv_context.is_empty() and app.ui.pv_context.ply==4,"board cached line previews from current report position")
	app.ui.stop_pv()
	await settle()
	check(app.ui.page==null and app.replay_index==4 and matching_cache(4),"board line returns to same board rather than wrong report page")
	app.ui.show_report()
	app.ui.select_report_move(4)
	await press("DismissReportMove")
	check(app.ui.page_name=="report" and app.ui.report_selected_ply==-1 and app.ui.report_chart.active==-1,"close control clears selection without opening board")
	app.ui.select_report_move(0)
	check(app.ui.report_selection.get_child_count()==0,"initial chart point does not create a fake move card")
	app.ui.close()
	await settle()
	check(not app.ui.report_board_active and app.ui.pv_rows.is_empty() and app.ui.live_details.is_empty(),"leaving report review removes cached analysis from live game")
	preserve("all compact report actions")
	check(report.game.to_data()==saved_report,"report line navigation never changes analyzed game")
	app.set_appearance("wood")
	app.ui.open_report_position(1)
	await until(func(): return app.motion_progress>=1)
	app.ui.open_report_position(2)
	await settle(0.07)
	check(app.motion_progress>0 and app.motion_progress<1,"3D report card navigation animates actual move")
	await capture("wood-report-animation")
	await until(func(): return app.motion_progress>=1)
	app.ui.show_report_move_details(2)
	await click("从这里下")
	check(app.review_game==null and app.game!=live and app.game.moves.size()==2,"details can start a playable game at selected report ply")
	check(app.game.position.key()==report.game.positions[2].key() and report.game.to_data()==saved_report,"continuation uses exact board and preserves full analyzed game")
	await capture("continue-from-details")
	FileAccess.open(output.path_join("results.json"),FileAccess.WRITE).store_string(JSON.stringify({"checks":checks,"failures":failures,"screenshots":screenshots},"  "))
	print("CHESSIS 16 UI: ",checks," checks; ",failures)
	app.get_tree().quit(0 if failures.is_empty() else 1)
