extends "res://tests/chessis23_test.gd"
var study
var source
var calls = 0

func edited() -> void:
	app.ui.start_variation_analysis(source, 1)
	study = app.ui.study
	app.preferences.studio.variation_policy = "never"
	app.preferences.studio.variation_policy_confirmed = true
	check(study.commit(app.Codec.parse_move("8c8d", study.current.position)), "legal alternative changes analysis")
	await settle(0.2)

func run(instance) -> void:
	app = instance
	output = ProjectSettings.globalize_path("res://../review/app/chessis34/ui")
	DirAccess.make_dir_recursive_absolute(output)
	app.records.root = output.path_join("records-" + str(Time.get_ticks_usec()))
	app.save_path = output.path_join("active.json")
	app.ui.tutorial.progress_path = output.path_join("learning.json")
	app.get_tree().create_timer(180).timeout.connect(func(): app.get_tree().quit(2))
	await resize(Vector2i(393, 852))
	app._start_match("local", 1, 2, "basic"); app.ui.close()
	app.preferences.studio.animation = 0.22
	app.ui.replace_game(func(): calls += 1)
	check(calls == 1 and app.records.list_all().is_empty(), "empty match replacement creates no archive or prompt")
	source = app.Game.new(); source.mode = "local"
	for text in ["7g7f", "3c3d", "8h2b+", "3a2b", "B*4e"]:
		check(source.play(app.Codec.parse_move(text, source.position)), "source move " + text)
	var original: Dictionary = source.to_data().duplicate(true)
	check(app.ui.analysis_import.open_game(source), "load replay without saving")
	app.ui.live_enabled = false
	for ply in [3, 0, 5, 2]: app.ui.show_history(ply); await settle(0.25)
	app.ui.close()
	check(app.records.list_all().is_empty() and source.to_data() == original, "plain replay does not create or alter any record")
	app.ui.start_variation_analysis(source, 1); study = app.ui.study
	check(study.record_path.is_empty() and not study.dirty, "entering analysis has no automatic save")
	study.seek(3); study.seek(0)
	check(not study.dirty and app.ui.finish_study(), "navigation alone exits without confirmation")
	check(app.records.list_all().is_empty(), "unchanged analysis creates no archive")
	await edited()
	check(study.dirty and study.record_path.is_empty() and app.records.list_all().is_empty(), "edits stay in memory until user saves")
	study.undo()
	check(not study.dirty, "undo back to original content clears unsaved status regardless of cursor")
	check(app.ui.finish_study(), "reverted edits exit without saving")
	await edited()
	check(not app.ui.finish_study() and app.ui.page_name == "save-study", "edited analysis asks how to leave")
	await capture("save-study-portrait")
	await press("CancelStudyExit")
	check(study.active and study.dirty and app.ui.page == null, "continue editing keeps unsaved changes")
	app.ui.live_key = study.current.position.key()
	app.ui.receive_info({"score": 20, "depth": 4, "pv": ["7f7e"], "multipv": 1})
	check(not app.ui.pv_rows.is_empty(), "edited study has actionable candidate row before exit")
	app.ui.finish_study()
	await press("DiscardStudyChanges")
	check(not study.active and app.records.list_all().is_empty() and source.to_data() == original, "discard leaves source and library untouched")
	check(app.ui.pv_rows.is_empty() and app.ui.live_details.is_empty() and app.ui.arrows.is_empty(), "discard removes candidate rows and arrows from the old study position")
	await edited()
	app.ui.finish_study()
	await press("SaveStudyChanges")
	var path: String = study.record_path
	check(not study.active and not path.is_empty() and app.records.list_all().size() == 1, "save on exit creates exactly one record")
	var stored = app.records.read(path)
	check(stored != null and stored.variation_tree.nodes.size() == 7 and stored.moves == source.moves, "saved record preserves main and alternative")
	var saved_bytes = FileAccess.get_file_as_bytes(path)
	app._load_archive(path); study.seek(2); app.ui.finish_study()
	check(FileAccess.get_file_as_bytes(path) == saved_bytes and app.records.list_all().size() == 1, "reopening and replaying a saved tree does not rewrite or duplicate it")
	app._load_archive(path)
	study.view.comments[str(app.replay_index)] = "未保存的注释"; study.persist_view()
	app.ui.finish_study(); await press("DiscardStudyChanges")
	check(FileAccess.get_file_as_bytes(path) == saved_bytes, "discarded annotation does not overwrite saved file")
	await edited()
	var blocker = output.path_join("blocked-parent")
	FileAccess.open(blocker, FileAccess.WRITE).store_string("Not a directory")
	study.record_path = blocker.path_join("record.json")
	app.ui.finish_study(); await press("SaveStudyChanges")
	check(study.active and study.dirty and app.ui.page_name == "save-study" and not study.error.is_empty(), "write failure leaves dialog and changes intact")
	await capture("save-study-error")
	study.record_path = ""
	await press("SaveStudyChanges")
	check(not study.active and app.records.list_all().size() == 2, "retry succeeds without duplicate partial records")
	await edited()
	app.ui.analysis_import.open_game(source)
	check(app.ui.page_name == "save-study", "loading another replay waits for edit decision")
	await press("DiscardStudyChanges")
	check(app.review_game == source and app.replay_index == 0 and not study.active, "pending import resumes after discard")
	app.ui.live_enabled = false; app.ui.close()
	app.game.play(app.Codec.parse_move("9g9f", app.game.position))
	var old_game = app.game
	app.ui.replace_game(func(): calls += 1)
	check(app.ui.page_name == "replace-game" and calls == 1, "played match waits for save choice")
	await press("CancelMatchExit")
	check(calls == 1 and app.game == old_game, "cancel replacement keeps current match")
	app.ui.replace_game(func(): calls += 1; app.ui.close())
	await capture("save-match-portrait")
	await press("DiscardMatchChanges")
	check(calls == 2 and app.records.list_all().size() == 2, "not saving match continues without writing")
	# Explicit save really writes to isolated test storage.
	app.testing = false
	app.ui.replace_game(func(): calls += 1; app.ui.close())
	await press("SaveMatchChanges")
	app.testing = true
	check(calls == 3 and app.records.list_all().size() == 3 and not app._has_archive_changes(), "save match writes once and marks current content saved")
	app.game.clock.configure(1)
	app.game.clock.remaining[1] -= 10
	check(not app._has_archive_changes(), "clock ticking does not make a saved record dirty")
	app.ui.replace_game(func(): calls += 1)
	check(calls == 4 and app.records.list_all().size() == 3, "already saved unchanged match is not saved again")
	app.game.comments["1"] = "原注释"; app._set_replay(1)
	app.ui.live_enabled = false; app.ui.update_ribbon()
	var node_count: int = app.ui.move_strip.get_child_count()
	var first = app.ui.move_strip.get_child(0)
	for i in range(30): app.ui.update_ribbon()
	check(app.ui.move_strip.get_child(0) == first and app.ui.move_strip.get_child_count() == node_count, "unchanged frame polling reuses ribbon controls")
	app.game.comments["1"] = "修改后的同一个注释"; app.ui.persist_viewed(); app.ui.update_ribbon()
	check(app.ui.live_text.text == "修改后的同一个注释", "editing existing comment invalidates ribbon even when comment count stays unchanged")
	app.archive_baseline = app.RecordChanges.game_signature(app.game)
	app.ui.analysis_import.open_game(source); app.ui.live_enabled = false
	app._set_replay(3); app.ui.branch_here()
	check(app.game.moves.size() == 3 and app.game.position.key() == source.positions[3].key(), "continue uses selected promoted position")
	check(not app._has_archive_changes(), "unchanged continuation is not yet a new record")
	app.ui.replace_game(func(): calls += 1)
	check(calls == 5, "unchanged continuation exits without save prompt")
	app.game.play(app.Codec.parse_move("3a2b", app.game.position))
	check(app._has_archive_changes(), "playing from continuation creates unsaved content")
	app.ui.analysis_import.show(0); app.ui.analysis_import.show_import_choice(source)
	await press("ImportWithoutSaving")
	check(app.review_game == source and app.records.list_all().size() == 3, "file choice can load without saving")
	app.ui.analysis_import.show(0); app.ui.analysis_import.show_import_choice(source)
	await press("ImportAndSave")
	check(app.records.list_all().size() == 4 and not app.review_path.is_empty(), "file choice can save then load")
	await edited()
	app.ui.analysis_import.show(0); app.ui.analysis_import.show_import_choice(source)
	await press("ImportAndSave")
	check(app.ui.page_name == "save-study", "file save waits for current study decision")
	await press("DiscardStudyChanges")
	check(app.records.list_all().size() == 5 and app.review_game == source, "file saving resumes directly after study decision")
	var next = app.Game.new(); next.mode = "local"
	app.ui.adopt_game(next, true)
	check(app.ui.page_name == "replace-game", "editor replacement waits for current match decision")
	await press("DiscardMatchChanges")
	check(app.game == next and app.flipped, "deferred editor replacement retains chosen orientation")
	for dimensions in [Vector2i(360, 760), Vector2i(852, 393)]:
		await resize(dimensions)
		await edited(); app.ui.finish_study()
		await settle(0.15)
		check(app.safe_rect().encloses(app.ui.page.get_global_rect()), "save decision fits " + str(dimensions))
		await capture("save-study-" + str(dimensions.x))
		await press("DiscardStudyChanges")
	app.ui.live_enabled = false; app._pause_search()
	await finish()
