extends "res://tests/chessis13_test.gd"

func run(instance) -> void:
	app = instance
	output = ProjectSettings.globalize_path("res://../review/app/chessis15/ui")
	if "--chessis16-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis16/story-ui")
	if "--chessis20-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis20/chessis15_test")
	if "--chessis17-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis17/story-ui")
	DirAccess.make_dir_recursive_absolute(output)
	app.records.root = output.path_join("records")
	app.ui.tutorial.progress_path = output.path_join("learning-test.json")
	app.get_tree().create_timer(180).timeout.connect(func(): app.get_tree().quit(2))
	app._start_match("local",1,2,"basic")
	app.ui.close()
	await play("7g7f")
	live = app.game
	saved_live = live.to_data().duplicate(true)
	report = app.ui.report
	practice = app.ui.practice
	var historic = preload("res://scripts/shogi_historic_games.gd").new()
	var source = historic.game_for(historic.entries()[0])
	report.start(source,false,{"quick_mode":"depth","quick_depth":3},{"threads":2,"hash":32})
	check(await until(func(): return report.rows.size() >= 18 or not report.running,20),"historical engine report begins")
	report.cancel()
	await resize(Vector2i(393,852))
	app.ui.show_report()
	check(not report.story().complete and not report.story().closed,"partial actual report does not narrate final outcome")
	check(app.ui.report_story.model.analyzed_plies == report.rows.size(),"partial summary reflects current analyzed prefix")
	await capture("partial-story")
	var prefix = report.samples.duplicate(true)
	report.resume()
	check(await until(func(): return report.rows.size() >= prefix.size() + 4 or not report.running,20),"open report continues receiving actual engine positions")
	check(app.ui.report_story.model.analyzed_plies == report.rows.size() and not app.ui.report_story.model.closed,"visible summary updates live without borrowing the future result")
	check(await until(func(): return not report.running,105),"complete actual historical report finishes")
	check(report.error.is_empty() and report.samples.size() == source.positions.size(),"every historical position has actual engine output")
	check(report.samples.slice(0,prefix.size()) == prefix,"resuming narrative preserves previous real scores")
	app.ui.show_report()
	var model = report.story()
	check(model.complete and model.closed and model.winner == source.winner,"summary uses actual completed historical result")
	check(model.moments.size() > 1 and model.moments.size() <= 10,"real game has expandable bounded turning points")
	for moment in model.moments:
		check(moment.before == report.samples[moment.ply-1] and moment.after == report.samples[moment.ply],"moment retains exact engine before/after evidence")
	FileAccess.open(output.path_join("actual-report.json"),FileAccess.WRITE).store_string(JSON.stringify({"source":report.game.to_data(),"samples":report.samples,"rows":report.rows,"story":model},"  "))
	for mode in ["dark","light"]:
		app.set_preference("color_mode",mode)
		for dimensions in [Vector2i(360,760),Vector2i(393,852),Vector2i(852,393),Vector2i(1100,800)]:
			await resize(dimensions)
			app.ui.show_report()
			await settle()
			check(app.ui.report_story.find_child("StoryMoments",true,false).get_child_count() == 1,"reference default shows one moment")
			var summary = app.ui.report_story.find_child("GameStorySummary",true,false)
			check(summary.get_global_rect().end.x <= app.ui.page.get_global_rect().end.x,"narrative stays inside report width")
			check(app.ui.report_story.find_children("StoryMoveTitle","Label",true,false).all(func(item): return item.get_line_count()==1),"moment move title never wraps vertically")
			check(app.ui.report_story.find_children("StoryMoveScore*","Label",true,false).size()==2,"before and after scores are visible")
			await capture("story-"+mode+"-%dx%d" % [dimensions.x,dimensions.y])
	await resize(Vector2i(393,852))
	app.set_preference("color_mode","dark")
	app.ui.show_report()
	await press("ToggleStoryMoments")
	check(app.ui.report_story.find_child("StoryMoments",true,false).get_child_count()==model.moments.size(),"expand reveals every selected turning point")
	await capture("expanded-moments")
	var target: int = model.moments[-1].ply
	await press("StoryMoment%d" % target)
	check(app.ui.report_selected_ply==target and app.ui.report_chart.active==target,"actual card touch selects matching graph move")
	await capture("selected-moment")
	await press("StoryMomentsHelp")
	check(app.ui.page_name=="report-story-info" and app.safe_rect().encloses(app.ui.page.get_global_rect()),"key moments explanation opens in bounded dialog")
	await capture("key-moments-help")
	app.ui.back()
	check(app.ui.report_selected_ply==target and app.ui.report_story_expanded,"help returns to prior selection and expansion")
	await press("ToggleStoryMoments")
	check(app.ui.report_story.find_child("StoryMoments",true,false).get_child_count()==1,"collapse restores one-moment view")
	preserve("all story actions")
	app.ui.close()
	FileAccess.open(output.path_join("results.json"),FileAccess.WRITE).store_string(JSON.stringify({"checks":checks,"failures":failures,"screenshots":screenshots},"  "))
	print("CHESSIS 15 UI: ",checks," checks; ",failures)
	app.get_tree().quit(0 if failures.is_empty() else 1)
