extends "res://tests/unified_test.gd"

func run(instance) -> void:
	app = instance
	output = ProjectSettings.globalize_path("res://../review/app/chessis")
	if "--chessis10-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis10/regression")
	if "--chessis11-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis11/regression")
	if "--chessis12-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis12/regression")
	if "--chessis13-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis13/regression")
	if "--chessis14-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis14/regression")
	if "--chessis15-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis15/regression")
	if "--chessis16-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis16/regression")
	if "--chessis20-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis20/chessis_ui_test")
	if "--chessis17-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis17/regression")
	DirAccess.make_dir_recursive_absolute(output)
	app.records.root = output.path_join("records")
	app.ui.tutorial.progress_path = output.path_join("tutorial-progress.json")
	app.get_tree().create_timer(110).timeout.connect(func(): app.get_tree().quit(2))
	app.set_preference("language", "zh")
	app.set_preference("color_mode", "dark")
	app._start_match("local", 1, 2, "basic")
	app.ui.show_home()
	check(app.ui.page == null, "board is entry screen")
	for dimensions in [Vector2i(393, 852), Vector2i(360, 760), Vector2i(1100, 800), Vector2i(852, 393)]:
		await resize(dimensions)
		await capture("board-%dx%d" % [dimensions.x, dimensions.y])
		check(app.safe_rect().encloses(app.board_rect), "board fits " + str(dimensions))
		check(app.ui.toolbar.get_child_count() == 8, "eight navigation controls including undo")
		check(app.ui.live_panel.get_global_rect().end.y <= app.ui.toolbar.position.y + 1, "analysis fits " + str(dimensions))
	await resize(Vector2i(393, 852))
	# Hidden Windows probes do not acquire application focus. Simulate foreground
	# before injecting player touches, as the engine-match check does below.
	print("BOARD TOUCH READY active=", app.active, " window=", app.get_window().size, " viewport=", app.get_viewport_rect().size)
	app.active = true
	check(app._can_play(), "foreground local board accepts player input")
	await tap(app.square_rect(56).get_center())
	check(app.selection == 56, "touch selects intended pawn")
	await tap(app.square_rect(47).get_center())
	await settle(0.3)
	check(app.game.moves.size() == 1, "touch board legal move")
	for value in ["3c3d", "8h2b+", "3a2b", "B*4e"]: await play(value)
	await capture("capture-drop")
	var key = app.game.position.key()
	app.ui.show_history(2)
	check(app.replay_index == 2 and app.game.position.key() == key, "replay isolates active game")
	app.ui.show_comment()
	var comment = app.ui.page.find_children("*", "TextEdit", true, false)[0]
	comment.text = "先开放角道，再观察飞车侧的进攻。"
	await click("保存注释")
	check(app.game.comments.get("2") == "先开放角道，再观察飞车侧的进攻。", "comment saved at replay ply")
	app.ui.start_drawing()
	await tap(app.square_rect(47).get_center())
	check(app.game.annotations.get("2", []).size() == 1, "touch circle annotation")
	app.ui.back()
	await capture("replay-annotation")
	app.ui.close()
	for entry in [["drawer", app.ui.show_drawer], ["play", app.ui.show_play], ["bots", app.ui.show_bots], ["setup", app.ui.show_setup], ["settings", app.ui.show_settings], ["board-settings", app.ui.show_board_settings], ["engine-settings", app.ui.show_engine_settings], ["editor", app.ui.show_editor], ["openings", app.ui.show_openings], ["more", app.ui.show_menu], ["export", app.ui.show_export], ["backup", app.ui.show_backup]]:
		entry[1].call()
		await settle(0.12)
		await capture(entry[0])
		check(app.ui.page != null, "route " + entry[0])
		check(app.safe_rect().encloses(app.ui.page.get_global_rect()), "page fits " + entry[0])
	app.ui.show_editor()
	app.ui.editor.pos.board[47] = 0
	check(app.game.position.key() == key, "editor is independent until applied")
	app.ui.close()
	app.ui.set_report_option("quick_mode", "time")
	app.ui.set_report_option("quick_time", 0.3)
	app.ui.start_report(false)
	check(await until(func(): return not app.ui.report.running, 35), "report terminates")
	check(app.ui.report.error.is_empty(), "report engine " + app.ui.report.error)
	check(app.ui.report.rows.size() == app.game.moves.size(), "report covers every move")
	app.ui.show_report()
	await settle(0.2)
	for summary_label in app.ui.page.find_children("ReportSideSummary", "Label", true, false):
		check(summary_label.size.x >= 120 and summary_label.size.y < 100, "report summary readable")
	await capture("game-report")
	app.ui.close()
	app.ui.show_analysis()
	check(await until(func(): return app.ui.live_details.size() > 0, 20), "live USI analysis")
	await settle(0.4)
	await capture("live-analysis")
	app.ui.live_enabled = false
	app._pause_search()
	app.set_preference("color_mode", "light")
	app.ui.close()
	await capture("board-light")
	app.ui.show_settings()
	await capture("settings-light")
	var backup = preload("res://scripts/shogi_backup.gd").new()
	app.preferences.studio.threads = 4
	var backup_data: Dictionary = backup.collect(app, app.ui.tutorial)
	app.preferences.studio.threads = 2
	var before_records = app.records.list_all().size()
	var restored = backup.restore(app, app.ui.tutorial, JSON.parse_string(JSON.stringify(backup_data)), true, true)
	check(restored >= 1 and backup.error.is_empty(), "backup restores all categories " + backup.error)
	check(app.preferences.studio.threads == 4, "restore numeric settings through JSON")
	check(app.records.list_all().size() > before_records, "restore archives active game")
	var invalid_backup = backup_data.duplicate(true)
	invalid_backup.records.append({"game": {"version": 44}})
	var count_before = app.records.list_all().size()
	check(backup.restore(app, app.ui.tutorial, invalid_backup, false, false) < 0, "reject corrupt backup before writes")
	check(app.records.list_all().size() == count_before, "corrupt backup leaves records intact")
	app.ui.show_setup(2)
	await click("开始")
	if app.ui.page_name == "replace-game": await click("保存并开始")
	check(app.game.engine_match and app.game.mode == "ai", "engine match starts after replacement")
	# Hidden test windows receive no foreground focus, and test startup disables AI.
	# Explicitly simulate foreground play before testing the real two-sided search.
	app.active = true
	app.auto_play = true
	check(not app._can_play() and await until(func(): return app.game.moves.size() >= 2, 15), "engine match makes real moves for both sides")
	app.auto_play = false
	app.ui.show_result()
	var file = FileAccess.open(output.path_join("results.json"), FileAccess.WRITE)
	file.store_string(JSON.stringify({"checks": checks, "failures": failures, "screenshots": screenshots}, "  "))
	print("CHESSIS UI: ", checks, " checks; ", failures)
	app.get_tree().quit(0 if failures.is_empty() else 1)
