extends "res://tests/unified_test.gd"

func capture(name: String) -> void:
	await settle(0.12)
	await app.get_tree().process_frame
	await RenderingServer.frame_post_draw
	app.get_viewport().get_texture().get_image().save_png(output.path_join(name + ".png"))
	screenshots.append(name)

func run(instance) -> void:
	app = instance
	output = ProjectSettings.globalize_path("res://../review/app/chessis10/ui")
	if "--chessis16-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis16/report-settings-ui")
	if "--chessis20-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis20/chessis10_test")
	if "--chessis17-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis17/report-settings-ui")
	if "--chessis11-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis11/report-ui")
	if "--chessis12-regression" in OS.get_cmdline_user_args(): output = ProjectSettings.globalize_path("res://../review/app/chessis12/report-ui")
	DirAccess.make_dir_recursive_absolute(output)
	app.records.root = output.path_join("records")
	app.get_tree().create_timer(120).timeout.connect(func(): app.get_tree().quit(2))
	app._start_match("local", 1, 2, "basic")
	app.ui.close()
	for value in ["7g7f", "3c3d", "8h2b+", "3a2b", "B*4e"]: await play(value)
	var original = app.game
	var original_key: String = original.position.key()
	await resize(Vector2i(393, 852))
	app.ui.show_report_settings()
	await capture("settings-default")
	check(app.ui.page.size.x < 393 and app.ui.page.size.x <= 420, "settings dialog uses original bounded width")
	check(app.ui.page.find_child("QuickValue", true, false).text.contains("14"), "quick default depth shown")
	app.ui.page.find_child("QuickTime", true, false).pressed.emit()
	check(app.preferences.report.quick_mode == "time", "time tab controls report mode")
	app.ui.page.find_child("QuickValue", true, false).pressed.emit()
	await settle()
	check(app.ui.page_name == "report-value", "analysis value dialog opens")
	app.ui.page.find_child("ReportValueInput", true, false).value = 2.3
	await capture("settings-time-picker")
	await click("确定")
	check(is_equal_approx(app.preferences.report.quick_time, 2.3), "edited time accepted")
	app.ui.page.find_child("SmartAnalysis", true, false).button_pressed = true
	check(app.preferences.report.smart and app.ui.page.find_child("QuickValue", true, false).text.contains("最大"), "smart changes value label to maximum")
	app.ui.page.find_child("DeepDepth", true, false).pressed.emit()
	app.ui.set_extra("analysis_lines", 2)
	var lines = app.ui.page.find_child("DeepLines", true, false)
	lines.select(2)
	lines.item_selected.emit(2)
	check(app.preferences.report.deep_lines == 3 and app.preferences.studio.analysis_lines == 2, "report and live settings independent")
	app.ui.set_report_option("deep_depth", 4)
	app.ui.set_report_option("smart", false)
	app.ui.show_report_settings()
	await capture("settings-configured")
	app.ui.start_report(true)
	check(app.ui.page == null and app.ui.report.running, "report starts inline")
	check(await until(func(): return not app.ui.report.running, 30), "real MultiPV depth report completes")
	check(app.ui.report.error.is_empty() and app.ui.report.samples.size() == 6, "actual report has every position")
	app.ui.show_report()
	await capture("report-overview")
	var chart = app.ui.report_chart
	app.ui.page_scroll.ensure_control_visible(chart)
	await settle()
	await tap(chart.global_position + Vector2(chart.size.x * 0.4, chart.size.y / 2))
	check(app.ui.page_name == "report" and app.ui.report_selected_ply >= 0, "chart tap keeps report open")
	check(app.game == original and app.game.position.key() == original_key, "chart selection does not mutate active game")
	app.ui.select_report_move(3)
	app.ui.page_scroll.scroll_vertical = 0
	await capture("report-selected-move")
	check(app.ui.report_selection.get_child_count() == 1 and app.ui.report_selection.find_child("ReportMoveCard", true, false) != null, "selected move has compact score transition card")
	app.ui.show_report_move_details(3)
	check(app.ui.page.find_children("ReportCandidatePreview*", "Button", true, false).size() == 3, "move details preserves all three analyzed alternatives")
	app.ui.show_report()
	app.ui.preview_report_line(2, app.ui.report.samples[2].candidates[0])
	await settle(0.25)
	check(app.ui.pv_context.get("report", false) and app.game == original, "report alternative previews independently")
	await capture("report-candidate-preview")
	app.ui.stop_pv()
	await settle()
	check(app.ui.page_name == "report" and app.ui.report_selected_ply == 3, "preview returns to selected report move")
	app.ui.report_moves_expanded = true
	app.ui.report_statistics.refresh_visibility()
	var pie = app.ui.page.find_child("SentePie", true, false)
	await settle(0.9)
	app.ui.page_scroll.ensure_control_visible(pie)
	await capture("report-pies")
	var segment: Dictionary = pie.ranges[0]
	var angle: float = segment.start + segment.sweep / 2
	await tap(pie.global_position + pie.geometry().center + Vector2.from_angle(angle) * pie.geometry().radius * 0.8)
	check(pie.active == segment.group and app.ui.page_name == "report", "pie opens quality insight inside report")
	check(app.ui.report_statistics.insight.visible and app.ui.report_statistics.insight_percent.text.contains("%"), "pie insight displays weighted percentage")
	await capture("report-category")
	app.ui.report_selected_ply = -1
	app.ui.show_report_settings()
	for dimensions in [Vector2i(360, 760), Vector2i(852, 393), Vector2i(1100, 800)]:
		await resize(dimensions)
		await capture("settings-%dx%d" % [dimensions.x, dimensions.y])
		check(app.safe_rect().encloses(app.ui.page.get_global_rect()), "settings fits " + str(dimensions))
	await resize(Vector2i(393, 852))
	app.set_preference("color_mode", "light")
	app.ui.show_report_settings()
	await capture("settings-light")
	app.ui.show_report()
	app.set_preference("color_mode", "dark")
	app.set_preference("color_mode", "light")
	check(app.ui.page.get_theme_stylebox("panel") is StyleBoxTexture, "live theme changes preserve textured report")
	await capture("report-light")
	FileAccess.open(output.path_join("results.json"), FileAccess.WRITE).store_string(JSON.stringify({"checks": checks, "failures": failures, "screenshots": screenshots}, "  "))
	print("CHESSIS 10 UI: ", checks, " checks; ", failures)
	app.get_tree().quit(0 if failures.is_empty() else 1)
