extends SceneTree
const History = preload("res://scripts/shogi_editor_history.gd")
const Analysis = preload("res://scripts/shogi_editor_analysis.gd")
const Rules = preload("res://scripts/shogi_rules.gd")
const Codec = preload("res://scripts/shogi_usi_codec.gd")
const Preferences = preload("res://scripts/shogi_preferences.gd")
var checks = 0
var failures = []

func check(value: bool, label: String) -> void:
	checks += 1
	if not value: failures.append(label); push_error(label)

func _initialize() -> void:
	var position = Rules.new()
	var original = Codec.sfen(position)
	var first = position.after(Codec.parse_move("7g7f", position))
	var second = first.after(Codec.parse_move("3c3d", first))
	var a = Codec.sfen(first)
	var b = Codec.sfen(second)
	var history = History.new()
	history.begin(original)
	check(history.entries == [original] and not history.can_undo() and not history.can_redo(), "opening creates one untouched setup")
	check(not history.push(original), "duplicate refresh does not consume undo history")
	history.push(a); history.push(b)
	check(history.undo() and history.current() == a and history.can_redo(), "undo restores exact turn, board and hands")
	check(history.redo() and history.current() == b, "redo restores exact setup")
	history.undo(); history.push(original)
	check(not history.can_redo(), "new edit drops redo branch")
	history.remember(a)
	check(history.entries == [original, a] and history.index == 1 and not history.can_undo(), "saving adds separate loaded setup")
	history.push(b)
	check(history.seek(0) and history.current() == original and history.can_undo(), "switching setups preserves first undo history")
	check(history.seek(1) and history.current() == b and history.can_undo(), "returning preserves second unsaved edit history")
	history.seek(0)
	history.remember(a)
	check(history.current() == a and history.entries.size() == 3, "saving a previous base cannot expose a different edited last setup")
	history.remember(a)
	check(history.entries.size() == 3, "saving the current unchanged setup does not duplicate it")
	check(not history.seek(-1) and not history.seek(99), "loaded setup navigation is bounded")
	for i in range(70):
		position.board[40] = 1 if i % 2 == 0 else 0
		history.push(Codec.sfen(position))
	check(history.histories.back().undo.size() == 50, "undo history has reference 50-state cap")
	var undone = 0
	while history.undo(): undone += 1
	check(undone == 49 and history.histories.back().redo.size() == 49, "undo cap retains newest states and bounded redo")
	for i in range(70): history.remember(a if i % 2 == 0 else b)
	check(history.entries.size() == 50 and history.histories.size() == 50 and history.index == 49, "saved setup cap evicts matching histories")
	var normalized = History.normalized([original, null, 1, "invalid", "a".repeat(513), "9/9/9/9/9/9/9/9/9 b - 1"])
	check(normalized == [original, "9/9/9/9/9/9/9/9/9 b - 1"], "editor can recover incomplete structural setups but rejects malformed saved data")
	var preferences = Preferences.new()
	preferences.studio.editor_positions = [original, "bad", a]
	preferences.studio.editor_eval_running = false
	preferences.save_to("user://editor27-test.cfg")
	var restored = Preferences.new()
	restored.load_from("user://editor27-test.cfg")
	check(restored.studio.editor_positions == [original, a] and restored.studio.editor_eval_bar and not restored.studio.editor_eval_running, "saved setup list and independent pause preference survive restart")
	DirAccess.remove_absolute("user://editor27-test.cfg")
	var analysis = Analysis.new()
	analysis.update(first, true)
	var generation = analysis.generation
	check(analysis.due >= Time.get_ticks_msec() + 240 and analysis.position != first, "edits schedule delayed analysis on a copy")
	analysis.receive(generation - 1, {"score": 999, "depth": 30})
	check(analysis.details.is_empty(), "stale generation cannot display an unrelated evaluation")
	analysis.receive(generation, {"score": -50, "depth": 4})
	check(analysis.details.score == -50, "current generation accepts real evaluation shape")
	analysis.update(first, true)
	check(analysis.generation == generation and analysis.details.score == -50, "palette and orientation refresh do not restart unchanged analysis")
	analysis.update(second, true)
	check(analysis.details.is_empty() and analysis.generation > generation, "changed board clears old score immediately")
	analysis.receive(generation, {"score": 500})
	check(analysis.details.is_empty(), "late result after an edit stays discarded")
	analysis.update(null, true)
	check(analysis.enabled and analysis.due == -1 and analysis.details.is_empty(), "incomplete text suspends evaluation without pretending user paused")
	analysis.update(Rules.new(false), true)
	analysis.receive(analysis.generation, {"score": 500})
	check(analysis.due == -1 and analysis.details.is_empty(), "invalid setup is never evaluated")
	analysis.update(first, false)
	analysis.receive(analysis.generation, {"score": 500})
	check(not analysis.enabled and analysis.due == -1 and analysis.details.is_empty(), "paused evaluator does not accept callbacks")
	analysis.update(first, true)
	analysis.receive(analysis.generation, {"score": 500, "bound": "lowerbound"})
	check(analysis.details.is_empty(), "bound-only score is not presented as exact")
	for retry in range(2):
		var old_generation = analysis.generation
		analysis.failed("injected failure")
		check(analysis.retries == retry + 1 and analysis.due >= Time.get_ticks_msec() + 490 and analysis.generation > old_generation, "engine failure schedules one of two bounded delayed retries")
		analysis.receive(old_generation, {"score": 500})
		check(analysis.details.is_empty(), "failed engine generation stays rejected")
	analysis.failed("injected final failure")
	check(analysis.due == -1 and not analysis.error.is_empty() and analysis.retries == 2, "repeated engine failure stops retrying with explicit error")
	analysis.update(second, true)
	check(analysis.retries == 0 and analysis.error.is_empty() and analysis.due >= 0, "new setup permits recovery after exhausted retries")
	var mate = Codec.parse_sfen("k8/1G7/R1K6/9/9/9/9/9/9 w - 1")
	check(Analysis.Game.position_error(mate).is_empty() and mate.legal_moves().is_empty(), "legal terminal setup is accepted with no playable moves")
	analysis.free()
	var output = ProjectSettings.globalize_path("res://../review/app/chessis27")
	DirAccess.make_dir_recursive_absolute(output)
	FileAccess.open(output.path_join("editor-core.json"), FileAccess.WRITE).store_string(JSON.stringify({"checks": checks, "failures": failures}, "  "))
	print("EDITOR 27: ", checks, " checks; ", failures)
	quit(0 if failures.is_empty() else 1)
