extends "res://tests/complete_ui_test.gd"

func run(instance) -> void:
	app = instance
	app.get_tree().create_timer(50).timeout.connect(func(): printerr("NETWORK UI TIMEOUT"); app.get_tree().quit(1))
	output = ProjectSettings.globalize_path("res://../review/app/complete")
	await settle()
	app.active = true
	print("QA dimensions ", app.size, " ", app.get_window().size, " ", app.get_viewport().get_visible_rect())
	await click_button("菜单")
	await click_button("网络对战")
	check(app.ui.page_name == "network", "network page opens from menu")
	await click_button("加入对局")
	await click_button("连接")
	check(app.session == null and app.ui.page_name == "join", "empty address rejected before connection")
	await capture("07-network-join")
	app.ui.show_host()
	await settle()
	app.ui.page.find_child("端口", true, false).text = "19322"
	await click_button("创建")
	check(app.session != null and app.session.is_host, "create starts actual listener")
	check(app.ui.connection_label != null and app.session.room_code in app.ui.connection_label.text, "host shows shareable room code")
	await capture("08-network-host")
	var remote = app.MatchSession.new()
	app.add_child(remote)
	remote.status_changed.connect(func(message): print("REMOTE: ", message))
	app.session.status_changed.connect(func(message): print("HOST: ", message))
	print("LISTEN: ", app.session.port, " ", app.session.room_code)
	check(remote.join_tcp("127.0.0.1", 19322, app.session.room_code) == OK, "second client joins through match API")
	check(await until(func(): return remote.connected_ready and app.session.connected_ready), "UI session handshake")
	await click_button("返回对局")
	app.active = true
	check(app._can_play(), "host UI allows own turn")
	app._tap(app.square_rect(app.Codec.parse_square("7g")).get_center())
	app._tap(app.square_rect(app.Codec.parse_square("7f")).get_center())
	check(await until(func(): return remote.game.moves.size() == 1), "board taps broadcast move")
	check(not app._can_play(), "board blocks opponent turn")
	check(remote.submit(app.Codec.parse_move("3c3d", remote.game.position)), "remote sends move")
	check(await until(func(): return app.game.moves.size() == 2 and remote.game.moves.size() == 2), "remote move reaches board and acknowledgement reaches peer")
	check(app.game.position.key() == remote.game.position.key(), "displayed game agrees with peer")
	check(remote.request("undo"), "remote requests undo")
	check(await until(func(): return app.ui.page_name == "offer"), "incoming offer opens actionable page")
	await capture("09-network-offer")
	await click_button("不同意")
	check(await until(func(): return remote.offer.is_empty()), "decline reaches remote")
	check(app.game.moves.size() == 2, "declining undo preserves game")
	check(remote.request("undo"), "remote requests undo again")
	check(await until(func(): return app.ui.page_name == "offer"), "second offer opens")
	await click_button("同意")
	check(await until(func(): return remote.game.moves.size() == 1), "accepted undo updates both games")
	remote.link.disconnect_peer()
	check(await until(func(): return not app.session.connected_ready), "UI detects disconnect")
	app.ui.close()
	app.active = true
	check(not app._can_play(), "disconnected UI cannot silently play locally")
	check(remote.reconnect() == OK, "remote reconnect")
	check(await until(func(): return app.session.connected_ready and remote.connected_ready), "UI resumes session")
	check(app.game.position.key() == remote.game.position.key(), "reconnected board exact")
	app.ui.show_connection()
	await settle()
	await click_button("退出联机")
	await click_button("保存棋谱并退出")
	check(app.session == null and app.game.moves.is_empty(), "explicit exit closes session and returns fresh game")
	remote.queue_free()
	app.ui.show_bluetooth()
	await capture("10-bluetooth-desktop")
	check(app.ui.page_name == "bluetooth", "Bluetooth platform availability page opens")
	await click_button("网络对战")
	check(app.ui.page_name == "network", "unsupported platform offers working network path")
	app.ui.close()
	var file = FileAccess.open(output.path_join("network-ui-tests.json"), FileAccess.WRITE)
	file.store_string(JSON.stringify({"checks": checks, "failures": failures}, "  "))
	file.close()
	print("NETWORK_UI_TESTS: ", checks, " checks, ", failures.size(), " failures")
	app.get_tree().quit(0 if failures.is_empty() else 1)
