import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/jinda/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:768,height:850}});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8765/review/inline-check.html');
const frame=page.frames().find(f=>f.parentFrame());
await frame.waitForFunction(()=>window.shogiReview?.ready,{timeout:45000});
await page.screenshot({path:'review/inline-light.png',fullPage:true});
await frame.getByRole('button',{name:'棋子细节',exact:true}).click();
await frame.locator('select').selectOption('pawn');
await frame.getByRole('button',{name:'查看背面',exact:true}).click();
await page.emulateMedia({colorScheme:'dark'});
await page.screenshot({path:'review/inline-dark.png',fullPage:true});
await page.setViewportSize({width:392,height:760});
await page.screenshot({path:'review/inline-narrow.png',fullPage:true});
const overflow=await frame.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
fs.writeFileSync('review/inline-checks.json',JSON.stringify({ready:true,errors,narrowOverflow:overflow},null,2));
await browser.close();
if(errors.length||overflow)throw new Error(JSON.stringify({errors,overflow}));
console.log('Inline CSP preview verified: 736/360 px, light/dark, piece selection and reverse face.');
