import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {validateBytes} from 'gltf-validator';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/jinda/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(import.meta.dirname,'..');
const results=[];
for(const file of fs.readdirSync(path.join(root,'models')).filter(f=>f.endsWith('.glb'))){
  const v=await validateBytes(new Uint8Array(fs.readFileSync(path.join(root,'models',file))),{uri:file});
  results.push({file,errors:v.issues.numErrors,warnings:v.issues.numWarnings,info:v.issues.numInfos,messages:v.issues.messages});
}
fs.writeFileSync(path.join(root,'review/validation.json'),JSON.stringify(results,null,2));
if(results.some(r=>r.errors))throw new Error('GLB validation failed');
const browser=await chromium.launch({headless:true,channel:'msedge',args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1600,height:1120},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8765',{waitUntil:'networkidle'});
await page.waitForFunction(()=>window.shogiReview?.ready,{timeout:30000});
await page.locator('.shogi-stage').screenshot({path:path.join(root,'review/01-scene.png')});
await page.screenshot({path:path.join(root,'review/review-desktop.png'),fullPage:true});
await page.getByRole('button',{name:'棋子细节',exact:true}).click();
await page.locator('select').selectOption('rook');
await page.locator('.shogi-stage').screenshot({path:path.join(root,'review/02-rook-front.png')});
await page.getByRole('button',{name:'查看背面',exact:true}).click();
await page.locator('.shogi-stage').screenshot({path:path.join(root,'review/03-rook-back.png')});
await page.getByRole('button',{name:'整体场景',exact:true}).click();
await page.evaluate(()=>{const r=window.shogiReview;r.camera.fov=34;r.camera.updateProjectionMatrix();r.camera.position.set(11,10,14);r.controls.update();r.draw();});
await page.locator('.shogi-stage').screenshot({path:path.join(root,'review/04-scene-angle.png')});
const before=await page.evaluate(()=>window.shogiReview.camera.position.toArray());
const bounds=await page.locator('.shogi-stage').boundingBox();
await page.mouse.move(bounds.x+bounds.width/2,bounds.y+bounds.height/2);await page.mouse.down();await page.mouse.move(bounds.x+bounds.width/2+100,bounds.y+bounds.height/2+40,{steps:8});await page.mouse.up();
const after=await page.evaluate(()=>window.shogiReview.camera.position.toArray());
if(JSON.stringify(before)===JSON.stringify(after))throw new Error('Orbit drag failed');
await page.setViewportSize({width:390,height:844});
await page.getByRole('button',{name:'整体场景',exact:true}).click();
await page.screenshot({path:path.join(root,'review/review-mobile.png'),fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
if(overflow)throw new Error('Mobile page overflow');
const metrics=await page.evaluate(()=>({triangles:window.shogiReview.renderer.info.render.triangles,drawCalls:window.shogiReview.renderer.info.render.calls,meshNodes:window.shogiReview.full.children.length}));
await browser.close();
fs.writeFileSync(path.join(root,'review/browser-checks.json'),JSON.stringify({errors,orbitDrag:true,mobileOverflow:overflow,metrics},null,2));
if(errors.length)throw new Error(errors.join('\n'));
console.log(JSON.stringify({models:results.length,validationErrors:0,validationWarnings:results.reduce((s,r)=>s+r.warnings,0),browserErrors:errors,orbitDrag:true,mobileOverflow:overflow,metrics},null,2));
